kind = "web"
previewPath = "/"
title = "flo."
version = "1.0.0"
id = "artifacts/flo"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20014

[services.development]
run = "pnpm --filter @workspace/flo run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/flo", "run", "build" ]
publicDir = "artifacts/flo/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20014"
BASE_PATH = "/"
