import { useLocation } from "wouter";
import Footer from "@/components/footer";

export default function PrivacyPage() {
  const [, setLocation] = useLocation();
  const today = "16 May 2026";

  return (
    <div className="min-h-[100dvh] bg-background text-foreground px-6 py-16 max-w-2xl mx-auto">
      <button onClick={() => setLocation("/")} className="text-xs text-muted-foreground hover:text-foreground transition-colors tracking-wide mb-12 block">
        ← back
      </button>

      <h1 className="text-5xl font-light italic tracking-tight text-primary mb-2">privacy.</h1>
      <p className="text-xs text-muted-foreground tracking-wide mb-16">last updated {today}</p>

      <div className="space-y-12 text-sm leading-relaxed text-foreground/80">

        <section className="space-y-4">
          <h2 className="text-xs tracking-widest uppercase text-muted-foreground">who we are</h2>
          <p>flo. is a personal daily briefing assistant developed by Locali Labs. This privacy policy explains how we collect, use, and protect your personal data when you use flo. We take privacy seriously and comply with the General Data Protection Regulation (GDPR) and applicable Danish and EU data protection law.</p>
          <p>Data controller: Locali Labs. For data requests, contact: <span className="text-foreground">privacy@localilabs.com</span></p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xs tracking-widest uppercase text-muted-foreground">what data we collect</h2>
          <p><span className="text-foreground">Account data.</span> When you sign in with Google, we receive your name, email address, and profile picture via Google OAuth. This is used to identify your account and personalise your briefing.</p>
          <p><span className="text-foreground">Calendar data.</span> With your explicit consent, flo. reads your Google Calendar and Apple Calendar (via CalDAV) events for today. This data is used solely to generate your daily briefing and is never stored permanently — it is fetched fresh each session.</p>
          <p><span className="text-foreground">Email data.</span> With your explicit consent, flo. reads the subject lines and body previews of your unread Gmail messages. These are summarised using AI and displayed in your briefing. Raw email content is never stored.</p>
          <p><span className="text-foreground">Location data.</span> flo. uses your device's GPS coordinates to fetch local weather. Coordinates are sent to our weather provider (Rainz) and are not stored on our servers. If you set a city override in settings, that city name is stored in your account preferences.</p>
          <p><span className="text-foreground">School data.</span> If you connect Aula, your login credentials are stored encrypted in our database. School messages and schedule data are fetched on demand and used to generate your briefing. This data is never shared with third parties.</p>
          <p><span className="text-foreground">Music data.</span> If you connect Spotify, your access token and refresh token are stored encrypted. flo. reads your top artists, top tracks, and playlist names to suggest music for your day. This data is not shared with third parties.</p>
          <p><span className="text-foreground">Schedule data.</span> Timetable entries you add manually or import are stored in our database associated with your account.</p>
          <p><span className="text-foreground">Chat history.</span> Messages you send to flo. and responses generated by our AI are stored in our database to provide conversation continuity. You can delete your chat history at any time from the settings screen.</p>
          <p><span className="text-foreground">Usage data.</span> We do not collect analytics, tracking pixels, or behavioural data. We do not use advertising cookies or cross-site tracking.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xs tracking-widest uppercase text-muted-foreground">how we use your data</h2>
          <p>All data collected by flo. is used exclusively for the following purposes:</p>
          <ul className="space-y-2 pl-4 list-disc text-foreground/70">
            <li>Generating your personalised daily briefing</li>
            <li>Powering AI-assisted chat about your day</li>
            <li>Fetching weather relevant to your location</li>
            <li>Suggesting playlists that match your day's context</li>
            <li>Storing your schedule and preferences across sessions</li>
          </ul>
          <p>We do not sell, rent, or share your personal data with any third party for marketing purposes.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xs tracking-widest uppercase text-muted-foreground">how we store your data</h2>
          <p>Your data is stored in Supabase, a PostgreSQL-based database hosted in the EU. Supabase encrypts data at rest and in transit using industry-standard TLS and AES-256 encryption.</p>
          <p>Sensitive credentials (Apple CalDAV passwords, Aula passwords, Spotify tokens) are stored in encrypted columns. Access tokens are scoped to the minimum permissions required.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xs tracking-widest uppercase text-muted-foreground">third-party services</h2>
          <p>flo. integrates with the following third-party services. Each operates under its own privacy policy:</p>
          <ul className="space-y-2 pl-4 list-disc text-foreground/70">
            <li><span className="text-foreground">Google</span> — authentication, calendar, and Gmail access. <a href="https://policies.google.com/privacy" className="underline">policies.google.com/privacy</a></li>
            <li><span className="text-foreground">Apple / iCloud</span> — CalDAV calendar and reminders access.</li>
            <li><span className="text-foreground">Aula</span> — Danish school communication platform.</li>
            <li><span className="text-foreground">Spotify</span> — music data and playlist access. <a href="https://www.spotify.com/legal/privacy-policy" className="underline">spotify.com/legal/privacy-policy</a></li>
            <li><span className="text-foreground">Groq</span> — AI language model inference for briefing generation and chat. Your data is sent to Groq's API and is subject to <a href="https://groq.com/privacy-policy" className="underline">Groq's privacy policy</a>. Groq does not use your data to train models by default.</li>
            <li><span className="text-foreground">Rainz</span> — weather data provider. Receives your GPS coordinates or city name to return weather information.</li>
            <li><span className="text-foreground">Supabase</span> — database and authentication infrastructure. <a href="https://supabase.com/privacy" className="underline">supabase.com/privacy</a></li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-xs tracking-widest uppercase text-muted-foreground">data retention</h2>
          <p>We retain your data for as long as your account is active. If you delete your account, all associated data — including briefings, chat history, schedules, and integration credentials — is permanently deleted within 30 days.</p>
          <p>Chat history can be deleted immediately from the settings screen. Integration credentials can be removed by disconnecting the relevant service in settings.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xs tracking-widest uppercase text-muted-foreground">your rights under GDPR</h2>
          <p>As a user in the EU, you have the following rights regarding your personal data:</p>
          <ul className="space-y-2 pl-4 list-disc text-foreground/70">
            <li><span className="text-foreground">Right of access</span> — you can request a copy of all data we hold about you.</li>
            <li><span className="text-foreground">Right to rectification</span> — you can request correction of inaccurate data.</li>
            <li><span className="text-foreground">Right to erasure</span> — you can request deletion of your data at any time.</li>
            <li><span className="text-foreground">Right to data portability</span> — you can request your data in a machine-readable format.</li>
            <li><span className="text-foreground">Right to restrict processing</span> — you can ask us to limit how we use your data.</li>
            <li><span className="text-foreground">Right to object</span> — you can object to processing based on legitimate interests.</li>
            <li><span className="text-foreground">Right to withdraw consent</span> — where processing is based on consent, you can withdraw it at any time.</li>
          </ul>
          <p>To exercise any of these rights, email us at <span className="text-foreground">privacy@localilabs.com</span>. We will respond within 30 days.</p>
          <p>You also have the right to lodge a complaint with the Danish Data Protection Authority (Datatilsynet) at <a href="https://www.datatilsynet.dk" className="underline text-foreground/60">datatilsynet.dk</a>.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xs tracking-widest uppercase text-muted-foreground">legal basis for processing</h2>
          <p>We process your data under the following legal bases as defined by GDPR Article 6:</p>
          <ul className="space-y-2 pl-4 list-disc text-foreground/70">
            <li><span className="text-foreground">Consent (Art. 6(1)(a))</span> — for accessing your calendar, email, school data, and music data. You grant these permissions explicitly when connecting each integration.</li>
            <li><span className="text-foreground">Contract performance (Art. 6(1)(b))</span> — for account data and preferences necessary to provide the service.</li>
            <li><span className="text-foreground">Legitimate interests (Art. 6(1)(f))</span> — for improving service reliability and preventing abuse.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-xs tracking-widest uppercase text-muted-foreground">changes to this policy</h2>
          <p>We may update this privacy policy from time to time. When we do, we will update the "last updated" date at the top of this page. Continued use of flo. after changes constitutes acceptance of the updated policy.</p>
        </section>

      </div>

      <Footer />
    </div>
  );
}
